export const GENRES = {
	'0': 'Не выбран',
	comedy: 'Комедия',
	drama: 'Драма',
	action: 'Боевик',
	thriller: 'Триллер',
	horror: 'Ужасы',
	family: 'Семейный',
	cartoon: 'Анимированный',
	fantasy: 'Фэнтези',
	romance: 'Романтика',
	adventure: 'Приключения',
	musical: 'Мьюзикл',
	war: 'Военный',
};
